# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'week9' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for week9
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKUser'
  pod 'KakaoSDKCommon'
end
